---
title: "Ch 14 Excercises"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.width = 12,
                      fig.asp = 0.7,
                      dpi = 200)
```

# Chapter 14 Excercises

## 1

**List the sample space for the following random experiment. First you toss a coin. Then, if you get a head, you throw a single die**

The sample space is follows
$\Omega = \{T, H-1, H-2, H-3, H-4, H-5, H-6\}$

## 3

**(a) The Number of alpha particles emitted by a radioactive sample in a fixed time interval is counted. Give the sample space for this experiment**

So, this is a slight trick, normally this would be a piosonn distribution, but in this case it can range anywhere from zero alpha particals, uptod the max that the sample can emit before it totally decays into a stable element.

**(b) The elapsed time is measured until the first alpha particle is emitted. Give the sample space for this experiment**

Same as before, ranging from T = 0, to t = Infinity (if it's a stable elemnt) BUT generally speaking, you could go up tot the halflife of this product.


## 5

** A box of n components has r (r < n) components which are defective. Components are tested one by one until all defective components are found, and the number of components tested is observed. Ddscribe the sample sapce for this experiment.**

The order of the testing doesn't mattter, we just have to figure out how to pull out all the defective items..SOOOOOO  

$\Omega = \frac{n!}{r!(n-r)!}$  

## 7

**Using the probability axioms show that**  
\[
P(\overline A \cap \overline B) = 1 - P(A \cup B)
\]

okay. so here we go

$P(\overline A \cap \overline B) = P(\overline {A \cup B}) $ bc $\overline A \cap \overline B = \overline {A \cup B}$
$  P(\overline {A \cup B})  = 1 - P(A  \cup B)$ bc $P(\overline A) = 1 - P(A)$  

**You may find it usefull to draw a Venn Diagram**  

## 9

**  When an experiment is performed, one and only one of the events A, B, or C will occur. Find P(A), P(B), and P(C) under each of the following assumptions: **  

**(a). P(A) = P(B) = P(C).**  
P(A) = P(C) = P(B) = 1/3  
**(b). P(A) = P(B) and P(C) = 1/4.**  
P($\Omega$) - P(C) = 1 - 1/4 = 3/4 = P(A) + P(B)
P(A) = P(B) = 3/8

**(c). P(A) = 2P(B) = 3P(C)** 
P($\Omega$) = 1 = P(A) + P(B) + P(C) = 3P(C) + 3/2 * P(C) + P(C) = 11/2 P(C) thus P(C) = 2/11, therefor P(A) = 6/11 and P(B) = 3/11

## 11

** Let A and B be events in a sample space such that P(A) = **$\alpha$**, P(B) = **$\beta$**, and **$P(A\cap B) = \gamma$**. Find an expression for the probabilities of the following events in terms of **$(\alpha, \beta, \gamma)$

**(a). **$\overline A\cap B$  
$P(\overline A \cap B) = P(B) - P(A \cap B) = \beta - gamma$  

**(b). **$A \cap\overline B$  
$P(A\cap\overline B) = P(A) - P(A \cap B) = \alpha - gamma$  

**(b). **$\overline A\cap\overline B$  
\[P(\overline A\cap\overline B) = P(\overline {A \cup B}) = 1 - P(A\cup B) = 1 - P(A) - P(B) - P(A\cap B) = 1 - \alpha -\beta - \gamma \]  



